import type { ReviewIssue } from "@/lib/ai-review";

const SEVERITY_EMOJI: Record<ReviewIssue["severity"], string> = {
  CRITICAL: "🔴",
  WARNING: "🟡",
  SUGGESTION: "🟢",
};

export const formatReviewComment = (
  issues: ReviewIssue[],
  prTitle: string
): string => {
  if (issues.length === 0) {
    return [
      "## 🤖 AI Code Review",
      "",
      `**PR:** ${prTitle}`,
      "",
      "✅ **No issues found!** The code looks good.",
    ].join("\n");
  }

  const critical = issues.filter((i) => i.severity === "CRITICAL");
  const warnings = issues.filter((i) => i.severity === "WARNING");
  const suggestions = issues.filter((i) => i.severity === "SUGGESTION");

  const lines: string[] = [
    "## 🤖 AI Code Review",
    "",
    `**PR:** ${prTitle}`,
    "",
    `**Summary:** ${critical.length} critical · ${warnings.length} warnings · ${suggestions.length} suggestions`,
    "",
    "---",
    "",
  ];

  // Group issues by file
  const byFile = issues.reduce<Record<string, ReviewIssue[]>>((acc, issue) => {
    if (!acc[issue.file]) acc[issue.file] = [];
    acc[issue.file].push(issue);
    return acc;
  }, {});

  for (const [file, fileIssues] of Object.entries(byFile)) {
    lines.push(`### 📄 \`${file}\``);
    lines.push("");

    for (const issue of fileIssues) {
      const emoji = SEVERITY_EMOJI[issue.severity];
      const location = issue.line ? ` (line ${issue.line})` : "";
      lines.push(`**${emoji} ${issue.severity}${location}:** ${issue.message}`);
      if (issue.suggestion) {
        lines.push(`> 💡 ${issue.suggestion}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("*Generated by [CodeReviewer AI](https://github.com)*");

  return lines.join("\n");
};
